### ISSUE TITLE
区域化线程转移导致崩溃

### ISSUE THREAD

**Issue by shulng** [LeavesMC/Lumina#21]
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerPlayer.chunkPosition()" because "player" is null
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:160) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:71) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.TickRegions$TickRegionData.split(TickRegions.java:271) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.split(ThreadedRegionizer.java:830) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.ThreadedRegionizer.onRegionRelease(ThreadedRegionizer.java:662) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.markNotTicking(ThreadedRegionizer.java:986) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.markNotTicking(TickRegions.java:389) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:434) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:36:18] [Region Scheduler Thread #0/ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Uncaught exception in tick thread "Region Scheduler Thread #0"
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.level.ServerPlayer.chunkPosition()" because "player" is null
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:160) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.RegionizedWorldData$1.split(RegionizedWorldData.java:71) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.TickRegions$TickRegionData.split(TickRegions.java:271) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.split(ThreadedRegionizer.java:830) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.ThreadedRegionizer.onRegionRelease(ThreadedRegionizer.java:662) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.ThreadedRegionizer$ThreadedRegion.markNotTicking(ThreadedRegionizer.java:986) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.markNotTicking(TickRegions.java:389) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:434) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[lumina-1.20.6.jar:1.20.6-DEV-5c8e48d]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by MC-XiaoHei** [comment]
麻烦发问题时候加上出现的情况（x

**Comment by shulng** [comment]
> 麻烦发问题时候加上出现的情况（x

这次就不清楚了，是玩着玩着突然崩的

**Comment by MC-XiaoHei** [comment]
我看看 好奇怪啊

**Comment by MC-XiaoHei** [comment]
是否有移除假人或者玩家移动的情况？

**Comment by shulng** [comment]
> 是否有移除假人或者玩家移动的情况？

**Comment by shulng** [comment]
> 是否有移除假人或者玩家移动的情况？

[2024-08-03-3.log](https://github.com/user-attachments/files/16477974/2024-08-03-3.log)

**Comment by MC-XiaoHei** [comment]
我看看

**Comment by MC-XiaoHei** [comment]
看了一下 就是tp时候出问题了。我看看怎么修

**Comment by shulng** [comment]
> 看了一下 就是tp时候出问题了。我看看怎么修

OK好的

**Comment by MC-XiaoHei** [comment]
似乎发现了问题 但我这边没条件复现，要不你试试新版？

**Comment by shulng** [comment]
> 似乎发现了问题 但我这边没条件复现，要不你试试新版？

![image](https://github.com/user-attachments/assets/4c8f7c95-5fc8-4d6d-acaa-4bb658eab988)

**Comment by MC-XiaoHei** [comment]
斯

**Comment by MC-XiaoHei** [comment]
试试新版（x

**Comment by MC-XiaoHei** [comment]
如果仍然有问题，请继续报告并尝试提供可复现方案

例如 在某处创建假人A TP到某处 ，然后在某处创建假人B，向前移动并等待（只是例子）

**Comment by shulng** [comment]
> 如果仍然有问题，请继续报告并尝试提供可复现方案
> 
> 例如 在某处创建假人A TP到某处 ，然后在某处创建假人B，向前移动并等待（只是例子）

ok好的

**Comment by MC-XiaoHei** [comment]
希望别出问题了（

**Comment by shulng** [comment]
> 希望别出问题了（

召唤的假人，过一会就会自动退出后台无报错

**Comment by MC-XiaoHei** [comment]
离谱 也没log吗。有没有退出提示那块

**Comment by shulng** [comment]
> 离谱 也没log吗。有没有退出提示那块

没只有这个提示
[14:04:18 WARN]: hsds was kicked due to keepalive timeout!
[14:04:18 INFO]: hsds lost connection: Timed out
[14:04:18 INFO]: hsds left the game

**Comment by MC-XiaoHei** [comment]
果然是timeout 晚上修吧（
最近bug真多

**Comment by MC-XiaoHei** [comment]
修好了 请查收

**Comment by MC-XiaoHei** [comment]
没有问题暂时关闭了，还有同样问题请reopen issue
