### ISSUE TITLE
在双维度机器中有概率因为Folia的多线程中的高延迟而新开门

### ISSUE THREAD

**Issue by VinsonFather** [LeavesMC/Lumina#26]
### 预期的行为 Expected behavior

正常情况下，当对好门后，双维度机器就可以正常运行

### 观测到的实际行为 Observed/Actual behavior

但在Folia中，尽管对好了门，但是因为Folia的多线程中的高延迟而有概率忽略原来对好的门而新生成一个门，导致串门

### 复现步骤 Steps/models to reproduce

建造一个猪人塔，反复进入将同的地狱门，有概率传送到另一个新的门

**Comment by MC-XiaoHei** [comment]
即使使用了你在#27中提到的视频中的32*32设计，也会新开门吗？

**Comment by MC-XiaoHei** [comment]
请提供可用的复现方案，我们这边没法复现

**Comment by VinsonFather** [comment]
> 即使使用了你在 #27 中提到的视频中的32*32设计，也会新开门吗？

暂时没测试，但在33*35的架构中，有概率会出现这样的情况

**Comment by VinsonFather** [comment]
在leaves 1.20.6版本中，对好门后，33*35版本的架构不会出现串门的情况，但在folia1.20.6版本中，会出现的新开门的情况。
同时我在本地架设folia 1.20.6服务器中，反复进入同个地狱门有概率出现这样的问题。

**Comment by MC-XiaoHei** [comment]
已经有修改方案，但是需要亿点点时间...
稍等吧，开学了 我也没办法

**Comment by VinsonFather** [comment]
> 已经有修改方案，但是需要亿点点时间... 稍等吧，开学了 我也没办法

az,小黑你啥时候上学

**Comment by MC-XiaoHei** [comment]
> > 已经有修改方案，但是需要亿点点时间... 稍等吧，开学了 我也没办法
> 
> az,小黑你啥时候上学

已经上学了 （x

**Comment by MC-XiaoHei** [comment]
请尝试使用最新版构建测试

**Comment by VinsonFather** [comment]
> 请尝试使用最新版构建测试

新版本的lumina在进入地狱时出现了类似区块无法加载的情况，退出服务器在进入时显示连接超时

机器：MacBook Pro M2 Pro 
macOS版本：macOS 12.7.6

日志：[15:13:39 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[15:13:40 INFO]: Loaded 1175 recipes
[15:13:40 INFO]: Loaded 1276 advancements
[15:13:41 INFO]: Starting minecraft server version 1.20.6
[15:13:41 INFO]: Loading properties
[15:13:41 WARN]: An expected class  org.bukkit.craftbukkit.scheduler.CraftScheduler$4 was not found for preloading: org.bukkit.craftbukkit.scheduler.CraftScheduler$4
[15:13:41 INFO]: This server is running Lumina version 1.20.6-DEV-master@f1d451d (2024-08-25T10:20:40Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
[15:13:41 INFO]: Server Ping Player Sample Count: 12
[15:13:41 INFO]: Using 4 threads for Netty based IO
[15:13:42 INFO]: Chunk system is using 1 I/O threads, 2 worker threads, and gen parallelism of 2 threads
[15:13:42 INFO]: Regionised ticking is enabled with 1 tick threads
[15:13:42 INFO]: Default game type: SURVIVAL
[15:13:42 INFO]: Generating keypair
[15:13:42 INFO]: Starting Minecraft server on *:25565
[15:13:42 INFO]: Using default channel type
[15:13:42 INFO]: Paper: Using libdeflate (macOS ARM64 / Apple Silicon) compression from Velocity.
[15:13:42 INFO]: Paper: Using native (macOS ARM64 / Apple Silicon) cipher from Velocity.
[15:13:42 INFO]: Command API is using NMS version 1_20_R4
[15:13:42 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:13:42 INFO]: Preparing level "world"
[15:13:43 INFO]: Preparing start region for dimension minecraft:overworld
[15:13:43 INFO]: Time elapsed: 1 ms
[15:13:43 INFO]: Preparing start region for dimension minecraft:the_nether
[15:13:43 INFO]: Time elapsed: 0 ms
[15:13:43 INFO]: Preparing start region for dimension minecraft:the_end
[15:13:43 INFO]: Time elapsed: 0 ms
[15:13:43 INFO]: Done (2.310s)! For help, type "help"
[15:13:43 INFO]: Initialising world 'world' before it can be ticked...
[15:13:43 INFO]: Initialised world 'world'
[15:13:43 INFO]: Initialising world 'world_nether' before it can be ticked...
[15:13:43 INFO]: Initialised world 'world_nether'
[15:13:43 INFO]: Initialising world 'world_the_end' before it can be ticked...
[15:13:43 INFO]: Initialised world 'world_the_end'
[15:13:47 INFO]: UUID of player ShiraiKuroko114 is 0624dc2e-9671-4f56-8537-1756d29eed8d
[15:13:47 INFO]: ShiraiKuroko114 joined the game
[15:13:47 INFO]: ShiraiKuroko114[/127.0.0.1:61926] logged in with entity id 35 at ([world]-38.0478158882623, 64.02442408821369, 298.981085644482)
[15:13:55 INFO]: ShiraiKuroko114 issued server command: /carpet:log
[15:13:59 INFO]: ShiraiKuroko114 issued server command: /carpet:log tps
[15:14:06 ERROR]: Failed to process chunk status callback
java.lang.NullPointerException: Cannot read field "minCorner" because "data" is null
	at org.leavesmc.lumina.utils.LevelNetherPortalPoiManager.toFoundRectangle(LevelNetherPortalPoiManager.java:245) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at org.leavesmc.lumina.utils.LevelNetherPortalPoiManager.findClosestPortal(LevelNetherPortalPoiManager.java:139) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at net.minecraft.world.entity.Entity.lambda$findOrCreatePortalAsync$15(Entity.java:4393) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at net.minecraft.server.level.ServerLevel.lambda$loadChunksAsync$0(ServerLevel.java:355) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.lambda$scheduleChunkLoad$6(ChunkTaskScheduler.java:519) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.lambda$completeStatusConsumers0$1(NewChunkHolder.java:1446) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:264) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1665) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[lumina-1.20.6.jar:1.20.6-DEV-f1d451d]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**Comment by MC-XiaoHei** [comment]
让我看看

**Comment by MC-XiaoHei** [comment]
这个bug应该在昨天推送的最新版本中修复了（x

**Comment by MC-XiaoHei** [comment]
经 @AilaSama 测试无问题，如还有问题请reopen
