### ISSUE TITLE
 #26 在双维度机器中有概率因为Folia的多线程中的高延迟而新开门

### ISSUE THREAD

**Issue by VinsonFather** [LeavesMC/Lumina#31]
### 预期的行为 Expected behavior

见 #26 在双维度机器中有概率因为Folia的多线程中的高延迟而新开门

### 观测到的实际行为 Observed/Actual behavior

见  #26 在双维度机器中有概率因为Folia的多线程中的高延迟而新开门

### 复现步骤 Steps/models to reproduce

见 #26 在双维度机器中有概率因为Folia的多线程中的高延迟而新开门

### 更多详细信息。 The more information.

之前提到的进入地狱门崩溃的问题已经解决了，但是#26的问题还是没有解决
现在我可以精准的复现出来

lumian服务器核心版本为三小时前发布的最新版本

复现步骤：
1，游戏难度设置为和平，同时使用litematica投影出猪人塔
2，来到主世界，对好门后（采用B站流行的对门方法：(x平/z平)*8+4）,进入主世界地狱门，来到地狱部分
3，传送后，来到了地狱猪人塔的中间，呆在地狱门里来回走动，充分加载地狱区块，卸载主世界区块（大概走动20s左右）
4，切换成观察者模式，在切换为创造模式，我们会立即传送到主世界
5，在主世界中，有1/10的概率会被传送到新开的地狱门，而有9/10的该是传送到对好的地狱门

另外我在leaves MC的交流1群中，叫中二的渣渣ZL，如果想要复现视频可以找我

**Comment by MC-XiaoHei** [comment]
虽然但是 其实我的意思是 reopen
而且你把lumin打错了 x
我看看

**Comment by VinsonFather** [comment]
> 虽然但是 其实我的意思是 reopen 而且你把lumin打错了 x 我看看

我还是个初中生我连reopen都不知道什么意思[狗头]

**Comment by MC-XiaoHei** [comment]
复现视频麻烦直接黏贴到这里吧

**Comment by VinsonFather** [comment]
> 复现视频麻烦直接黏贴到这里吧

视频太大了，我QQ发给你，群里面那个Sun. 是你吗

**Comment by VinsonFather** [comment]
> 复现视频麻烦直接黏贴到这里吧

复现视频太大了，我发到LeavesMC 核心测逝群里了

**Comment by VinsonFather** [comment]
现在我怀疑是对门的问题，我等会用leaves测试下（x/y）*8这种方法，而不是（x/y）*8+4
另外之前主世界进入地狱门的bug又在新版本出现了

日志：[10:19:45 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[10:19:46 INFO]: Loaded 1175 recipes
[10:19:46 INFO]: Loaded 1276 advancements
[10:19:47 INFO]: Starting minecraft server version 1.20.6
[10:19:47 INFO]: Loading properties
[10:19:47 WARN]: An expected class  org.bukkit.craftbukkit.scheduler.CraftScheduler$4 was not found for preloading: org.bukkit.craftbukkit.scheduler.CraftScheduler$4
[10:19:47 INFO]: This server is running Lumina version 1.20.6-DEV-master@7011e1c (2024-08-27T06:55:55Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
[10:19:47 INFO]: Using 4 threads for Netty based IO
[10:19:47 INFO]: Server Ping Player Sample Count: 12
[10:19:48 INFO]: Chunk system is using 1 I/O threads, 2 worker threads, and gen parallelism of 2 threads
[10:19:48 INFO]: Regionised ticking is enabled with 1 tick threads
[10:19:48 INFO]: Default game type: SURVIVAL
[10:19:48 INFO]: Generating keypair
[10:19:48 INFO]: Starting Minecraft server on *:25565
[10:19:48 INFO]: Using default channel type
[10:19:48 INFO]: Paper: Using libdeflate (macOS ARM64 / Apple Silicon) compression from Velocity.
[10:19:48 INFO]: Paper: Using native (macOS ARM64 / Apple Silicon) cipher from Velocity.
[10:19:49 INFO]: Command API is using NMS version 1_20_R4
[10:19:49 INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:19:49 INFO]: Preparing level "world"
[10:19:49 INFO]: Preparing start region for dimension minecraft:overworld
[10:19:49 INFO]: Time elapsed: 0 ms
[10:19:49 INFO]: Preparing start region for dimension minecraft:the_nether
[10:19:49 INFO]: Time elapsed: 0 ms
[10:19:49 INFO]: Preparing start region for dimension minecraft:the_end
[10:19:49 INFO]: Time elapsed: 0 ms
[10:19:49 INFO]: Done (1.990s)! For help, type "help"
[10:19:49 INFO]: Initialising world 'world' before it can be ticked...
[10:19:49 INFO]: Initialised world 'world'
[10:19:49 INFO]: Initialising world 'world_nether' before it can be ticked...
[10:19:49 INFO]: Initialised world 'world_nether'
[10:19:49 INFO]: Initialising world 'world_the_end' before it can be ticked...
[10:19:49 INFO]: Initialised world 'world_the_end'
[10:19:55 INFO]: UUID of player ShiraiKuroko114 is 0624dc2e-9671-4f56-8537-1756d29eed8d
[10:19:55 INFO]: ShiraiKuroko114 joined the game
[10:19:55 INFO]: ShiraiKuroko114[/127.0.0.1:64940] logged in with entity id 52 at ([world]16547.600212246605, -1.0, 16148.985820989343)
[10:20:19 ERROR]: Failed to process chunk status callback
java.lang.ArrayIndexOutOfBoundsException: Index 18 out of bounds for length 18
	at org.leavesmc.lumina.utils.LevelNetherPortalPoiManager.getMaxDistanceSqr(LevelNetherPortalPoiManager.java:199) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at org.leavesmc.lumina.utils.LevelNetherPortalPoiManager.findClosestPortal(LevelNetherPortalPoiManager.java:157) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at net.minecraft.world.entity.Entity.lambda$findOrCreatePortalAsync$15(Entity.java:4393) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at net.minecraft.server.level.ServerLevel.lambda$loadChunksAsync$0(ServerLevel.java:355) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.lambda$scheduleChunkLoad$6(ChunkTaskScheduler.java:519) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.lambda$completeStatusConsumers0$1(NewChunkHolder.java:1446) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:264) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1665) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:408) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[lumina-1.20.6.jar:1.20.6-DEV-7011e1c]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[10:20:37 INFO]: UUID of player ShiraiKuroko114 is 0624dc2e-9671-4f56-8537-1756d29eed8d
[10:20:41 INFO]: ShiraiKuroko114 (/127.0.0.1:64959) lost connection: Disconnected

进去服务器一直显示"通讯加密中..."

**Comment by VinsonFather** [comment]
已经是猪人塔的设计有缺陷，close了吧

**Comment by MC-XiaoHei** [comment]
草 但是你说的那个bug是有的。我等会修

**Comment by MC-XiaoHei** [comment]
你那个exception抛出的时候主世界门y有没有大于320或者小于0？

**Comment by Tan1103** [comment]
![截屏2024-08-28 15 45 25](https://github.com/user-attachments/assets/148bfbc7-1e92-48ed-8cb2-df41ce7b3e6c)
y=-1

**Comment by MC-XiaoHei** [comment]
y=-1是新门吗？
现在的算法确实有点问题 晚上修修

**Comment by Tan1103** [comment]
> y=-1是新门吗？ 现在的算法确实有点问题 晚上修修

啥意思

**Comment by MC-XiaoHei** [comment]
所以我没太看明白。现在issue所说的问题（错误的创建新门）还存在吗？
以及我的问题是 主世界不存在门的时候从地狱传送过去会不会报错？主世界传送到地狱 如果主世界门 y<0 或 y>320 的时候会不会报错

**Comment by Tan1103** [comment]
> 所以我没太看明白。现在issue所说的问题（错误的创建新门）还存在吗？ 以及我的问题是 主世界不存在门的时候从地狱传送过去会不会报错？主世界传送到地狱 如果主世界门 y<0 或 y>320 的时候会不会报错

1,错误的传送新门的这个问题《应该》不存在，可能是猪人塔的设计有缺陷
2,主世界不存在门的时候从地狱传送过去不会报错

**Comment by Tan1103** [comment]
第三个问题因为现在又正常不会崩溃了，所以回答不了
